apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-keycloak-stage
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform-blueprint
    app.kubernetes.io/component: authn-authz
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/environment: stage
spec:
  project: platform-stage
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  source:
    repoURL: https://codecentric.github.io/helm-charts
    chart: keycloakx
    targetRevision: 7.1.9
    helm:
      releaseName: keycloak
      values: |
        image:
          repository: quay.io/keycloak/keycloak
          tag: "26.5.5"
          pullPolicy: IfNotPresent
        args:
          - start
        proxy:
          enabled: true
          mode: xforwarded
          http:
            enabled: true
        http:
          relativePath: "/"
        service:
          type: ClusterIP
          httpPort: 80
        extraEnv: |
          - name: KC_DB_URL_HOST
            valueFrom:
              secretKeyRef:
                name: keycloak-runtime-credentials
                key: KEYCLOAK_DATABASE_HOST
          - name: KC_DB_URL_PORT
            valueFrom:
              secretKeyRef:
                name: keycloak-runtime-credentials
                key: KEYCLOAK_DATABASE_PORT
          - name: KC_DB_URL_DATABASE
            valueFrom:
              secretKeyRef:
                name: keycloak-runtime-credentials
                key: KEYCLOAK_DATABASE_NAME
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-runtime-credentials
                key: KEYCLOAK_DATABASE_USERNAME
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: "admin"
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-runtime-credentials
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: KC_HOSTNAME
            value: "auth.example.invalid"
          - name: KC_PROXY_HEADERS
            value: "xforwarded"
          - name: KC_HOSTNAME_STRICT
            value: "false"
        database:
          vendor: postgres
          hostname: ""
          port: ""
          database: ""
          username: ""
          existingSecret: keycloak-runtime-credentials
          existingSecretKey: KEYCLOAK_DATABASE_PASSWORD
        extraManifests: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
