apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets-store-csi-driver-vault-provider-stage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: platform-blueprint
    app.kubernetes.io/component: core-runtime
    app.kubernetes.io/name: secrets-store-csi-driver-vault-provider
    app.kubernetes.io/environment: stage
spec:
  project: platform-stage
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault-csi-provider
    targetRevision: 0.5.0
    helm:
      releaseName: vault-csi-provider
      values: |
        vaultAddress: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
