apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appproject.yaml
  - appproject-edge.yaml
  - applicationset-platform-environments.yaml
  - ../../core/dev/keycloak.yaml
  - ../../core/dev/secrets-store-csi-driver.yaml
  - ../../core/dev/secrets-store-csi-driver-vault-provider.yaml
