SHELL := /bin/bash
.DEFAULT_GOAL := help

# Blueprint-managed generated targets (rendered by make blueprint-render-makefile).
# Do not edit this file directly; edit scripts/templates/blueprint/bootstrap/make/blueprint.generated.mk.tmpl.
BLUEPRINT_MAKEFILE ?= make/blueprint.generated.mk

# Platform-owned targets (seeded once by blueprint bootstrap, then editable by consumers).
PLATFORM_MAKEFILE ?= make/platform.mk
PLATFORM_MAKEFILES_DIR ?= make/platform

include $(BLUEPRINT_MAKEFILE)
-include $(PLATFORM_MAKEFILE)
-include $(wildcard $(PLATFORM_MAKEFILES_DIR)/*.mk)
