apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - appproject.yaml
  - appproject-edge.yaml
  - application-platform-local.yaml
  - ../../core/local/keycloak.yaml
configMapGenerator:
  - name: blueprint-runtime-profile
    literals:
      - BLUEPRINT_ENV=local
      - DEPLOYMENT_MODEL=local-kustomize
generatorOptions:
  disableNameSuffixHash: true
