apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - runtime-contract-configmap.yaml
commonLabels:
  app.kubernetes.io/part-of: platform-blueprint
  app.kubernetes.io/environment: dev
