#!/usr/bin/env python3
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.lib.blueprint.cli_support import (  # noqa: E402
    display_repo_path,
    resolve_repo_path,
    resolve_repo_root,
)
from scripts.lib.blueprint.contract_schema import (  # noqa: E402
    ModuleContract,
    load_blueprint_contract,
    load_module_contract,
)


@dataclass(frozen=True)
class ModuleMetadata:
    contract_path: str
    module_id: str
    purpose: str
    enabled_by_default: str
    enable_flag: str
    make_targets: list[str]
    required_env: list[str]
    outputs: list[str]


@dataclass(frozen=True)
class OptionalRuntimeContractMetadata:
    contract_id: str
    enabled_by_default: str
    enable_flag: str
    summary: str


def _to_metadata(contract: ModuleContract) -> ModuleMetadata:
    return ModuleMetadata(
        contract_path=contract.contract_path,
        module_id=contract.module_id,
        purpose=contract.purpose,
        enabled_by_default=str(contract.enabled_by_default).lower(),
        enable_flag=contract.enable_flag,
        make_targets=list(contract.make_targets.values()),
        required_env=contract.required_env,
        outputs=contract.outputs,
    )


def _mapping(value: object) -> dict[str, Any]:
    if isinstance(value, dict):
        return {str(key): item for key, item in value.items()}
    return {}


def _string(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (int, float, bool)):
        return str(value)
    return ""


def _bool_text(value: object) -> str:
    if isinstance(value, bool):
        return str(value).lower()
    return "false"


def _list_of_str(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value]


def render_markdown(
    contract_name: str,
    contract_version: str,
    profiles: list[str],
    required_targets: list[str],
    modules: list[ModuleMetadata],
    optional_runtime_contracts: list[OptionalRuntimeContractMetadata],
    event_contract: dict[str, Any],
    app_runtime_gitops_contract: dict[str, Any],
    local_post_deploy_hook_contract: dict[str, Any],
    zero_downtime_contract: dict[str, Any],
    tenant_context_contract: dict[str, Any],
) -> str:
    lines: list[str] = []
    lines.append("<!-- Generated by scripts/lib/docs/generate_contract_docs.py. -->")
    lines.append("<!-- Source of truth: blueprint/contract.yaml and blueprint/modules/*/module.contract.yaml. -->")
    lines.append("")
    lines.append("# Contract Metadata (Generated)")
    lines.append("")
    lines.append(f"- Contract name: `{contract_name}`")
    lines.append(f"- Contract version: `{contract_version}`")
    lines.append("")
    lines.append("## Supported Profiles")
    for profile in profiles:
        lines.append(f"- `{profile}`")
    lines.append("")
    lines.append("## Required Make Targets")
    for target in required_targets:
        lines.append(f"- `{target}`")
    lines.append("")
    lines.append("## Optional Modules")
    lines.append("| Module | Enabled by default | Enable flag | Contract path |")
    lines.append("|---|---:|---|---|")
    for module in modules:
        lines.append(
            f"| `{module.module_id}` | `{module.enabled_by_default}` | "
            f"`{module.enable_flag}` | `{module.contract_path}` |"
        )
    lines.append("")

    lines.append("## Optional Runtime Contracts")
    lines.append("| Contract | Enabled by default | Enable flag | Summary |")
    lines.append("|---|---:|---|---|")
    for contract_item in optional_runtime_contracts:
        lines.append(
            f"| `{contract_item.contract_id}` | `{contract_item.enabled_by_default}` | "
            f"`{contract_item.enable_flag}` | {contract_item.summary} |"
        )
    lines.append("")

    event_envelope = _mapping(event_contract.get("envelope"))
    event_versioning = _mapping(event_contract.get("versioning_policy"))
    event_reliability = _mapping(event_contract.get("reliability"))
    event_scaffolding = _mapping(event_contract.get("scaffolding_hooks"))
    lines.append("## Runtime Contract: `event_messaging_contract`")
    lines.append("")
    lines.append("### Envelope Required Fields")
    for field in _list_of_str(event_envelope.get("required_fields")):
        lines.append(f"- `{field}`")
    lines.append("")
    lines.append("### Envelope Optional Fields")
    for field in _list_of_str(event_envelope.get("optional_fields")):
        lines.append(f"- `{field}`")
    lines.append("")
    lines.append("### Versioning Policy")
    lines.append(
        "- Additive default: "
        f"`{_bool_text(event_versioning.get('additive_evolution_default'))}`"
    )
    lines.append(
        "- Overlap window releases: "
        f"`{_string(event_versioning.get('overlap_window_releases'))}`"
    )
    lines.append(
        "- Deprecation window releases: "
        f"`{_string(event_versioning.get('deprecation_window_releases'))}`"
    )
    lines.append("")
    lines.append("### Reliability and Scaffolding Hooks")
    for key in (
        "producer_contract_dir",
        "consumer_contract_dir",
        "outbox_template_path",
        "inbox_template_path",
        "idempotency_template_path",
    ):
        value = _string(event_scaffolding.get(key))
        if value:
            lines.append(f"- `{key}`: `{value}`")
    retry = _mapping(event_reliability.get("retry"))
    if retry:
        lines.append(f"- `retry.strategy`: `{_string(retry.get('strategy'))}`")
    lines.append("")

    app_runtime_required_paths = _list_of_str(app_runtime_gitops_contract.get("required_paths_when_enabled"))
    app_runtime_required_kinds = _list_of_str(app_runtime_gitops_contract.get("workload_kinds_required_when_enabled"))
    app_runtime_smoke_guardrails = _mapping(app_runtime_gitops_contract.get("smoke_guardrails"))
    lines.append("## Runtime Contract: `app_runtime_gitops_contract`")
    lines.append("")
    lines.append(f"- Mode: `{_string(app_runtime_gitops_contract.get('mode'))}`")
    lines.append(f"- App catalog manifest path: `{_string(app_runtime_gitops_contract.get('app_catalog_manifest_path'))}`")
    lines.append("")
    lines.append("### Required Runtime Paths (When Enabled)")
    for path in app_runtime_required_paths:
        lines.append(f"- `{path}`")
    lines.append("")
    lines.append("### Required Workload Kinds (When Enabled)")
    for kind in app_runtime_required_kinds:
        lines.append(f"- `{kind}`")
    lines.append("")
    lines.append("### Smoke Guardrails")
    lines.append(f"- App namespace: `{_string(app_runtime_smoke_guardrails.get('app_namespace'))}`")
    lines.append(
        f"- Minimum workloads env var: `{_string(app_runtime_smoke_guardrails.get('minimum_workloads_env'))}`"
    )
    lines.append(
        f"- Minimum workloads default: `{_string(app_runtime_smoke_guardrails.get('minimum_workloads_default'))}`"
    )
    lines.append(f"- Diagnostics reason: `{_string(app_runtime_smoke_guardrails.get('diagnostics_reason'))}`")
    for kind in _list_of_str(app_runtime_smoke_guardrails.get("workload_kinds")):
        lines.append(f"- Smoke workload kind: `{kind}`")
    lines.append("")

    post_deploy_profiles = _list_of_str(local_post_deploy_hook_contract.get("run_profiles"))
    post_deploy_required_paths = _list_of_str(local_post_deploy_hook_contract.get("required_paths_when_enabled"))
    lines.append("## Runtime Contract: `local_post_deploy_hook_contract`")
    lines.append("")
    lines.append(f"- Invocation target: `{_string(local_post_deploy_hook_contract.get('invocation_target'))}`")
    lines.append(f"- Invocation script: `{_string(local_post_deploy_hook_contract.get('invocation_script'))}`")
    lines.append(f"- Consumer target: `{_string(local_post_deploy_hook_contract.get('consumer_target'))}`")
    lines.append(f"- Command env var: `{_string(local_post_deploy_hook_contract.get('command_env_var'))}`")
    lines.append(f"- Strict-mode env var: `{_string(local_post_deploy_hook_contract.get('strict_mode_env_var'))}`")
    lines.append(f"- State artifact path: `{_string(local_post_deploy_hook_contract.get('state_artifact_path'))}`")
    lines.append("")
    lines.append("### Run Profiles")
    for profile in post_deploy_profiles:
        lines.append(f"- `{profile}`")
    lines.append("")
    lines.append("### Required Paths (When Enabled)")
    for path in post_deploy_required_paths:
        lines.append(f"- `{path}`")
    lines.append("")

    zero_lifecycle = _mapping(zero_downtime_contract.get("lifecycle"))
    zero_db = _mapping(zero_downtime_contract.get("database_policy"))
    zero_api = _mapping(zero_downtime_contract.get("api_policy"))
    zero_events = _mapping(zero_downtime_contract.get("event_policy"))
    lines.append("## Runtime Contract: `zero_downtime_evolution_contract`")
    lines.append("")
    lines.append("### Lifecycle Phases")
    for phase in _list_of_str(zero_lifecycle.get("phases")):
        lines.append(f"- `{phase}`")
    lines.append("")
    lines.append("### Policy Highlights")
    lines.append(
        "- Destructive changes only in contract phase: "
        f"`{_bool_text(zero_lifecycle.get('destructive_changes_only_in_contract_phase'))}`"
    )
    lines.append(
        "- API additive default: "
        f"`{_bool_text(zero_api.get('additive_changes_default'))}`"
    )
    lines.append(
        "- Event additive default: "
        f"`{_bool_text(zero_events.get('additive_evolution_default'))}`"
    )
    lines.append(
        "- DB expand-first required: "
        f"`{_bool_text(zero_db.get('backward_compatible_expand_first'))}`"
    )
    lines.append("")

    tenant_identity = _mapping(tenant_context_contract.get("identity"))
    tenant_http = _mapping(tenant_context_contract.get("http_api"))
    tenant_events = _mapping(tenant_context_contract.get("async_events"))
    tenant_observability = _mapping(tenant_context_contract.get("observability"))
    lines.append("## Runtime Contract: `tenant_context_contract`")
    lines.append("")
    lines.append("### Required Claims")
    for claim in _list_of_str(tenant_identity.get("required_claims")):
        lines.append(f"- `{claim}`")
    lines.append("")
    lines.append("### Required HTTP Headers")
    tenant_headers = _mapping(tenant_http.get("required_headers"))
    for key in ("tenant_id", "organization_id", "correlation_id"):
        value = _string(tenant_headers.get(key))
        lines.append(f"- `{key}`: `{value}`")
    lines.append("")
    lines.append("### Async Event Fields")
    for field in _list_of_str(tenant_events.get("required_fields")):
        lines.append(f"- `{field}`")
    lines.append("")
    lines.append("### Observability Fields")
    for field in _list_of_str(tenant_observability.get("log_fields")):
        lines.append(f"- `{field}`")
    lines.append("")

    for module in modules:
        lines.append(f"## Module: `{module.module_id}`")
        lines.append("")
        lines.append(f"- Purpose: {module.purpose}")
        lines.append(f"- Enabled by default: `{module.enabled_by_default}`")
        lines.append(f"- Enable flag: `{module.enable_flag}`")
        lines.append("")
        lines.append("### Required Environment Variables")
        for item in module.required_env:
            lines.append(f"- `{item}`")
        lines.append("")
        lines.append("### Make Targets")
        for item in module.make_targets:
            lines.append(f"- `{item}`")
        lines.append("")
        lines.append("### Produced Outputs")
        for item in module.outputs:
            lines.append(f"- `{item}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help="Repository root used to resolve relative contract/modules/output paths.",
    )
    parser.add_argument(
        "--contract",
        type=Path,
        default=Path("blueprint/contract.yaml"),
        help="Path to platform contract YAML",
    )
    parser.add_argument(
        "--modules-dir",
        type=Path,
        default=Path("blueprint/modules"),
        help="Directory containing module.contract.yaml files",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/reference/generated/contract_metadata.generated.md"),
        help="Output generated markdown path",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when output file is out of date.",
    )
    args = parser.parse_args()

    # Shell wrappers resolve their own ROOT_DIR, so the Python helper must keep
    # relative paths anchored to the repository root instead of the caller cwd.
    repo_root = resolve_repo_root(args.repo_root, __file__)
    contract_path = resolve_repo_path(repo_root, args.contract)
    modules_dir = resolve_repo_path(repo_root, args.modules_dir)
    output_path = resolve_repo_path(repo_root, args.output)

    contract = load_blueprint_contract(contract_path)
    profiles = contract.raw.get("spec", {}).get("profiles", {}).get("supported", [])
    if not isinstance(profiles, list):
        raise ValueError("spec.profiles.supported must be a list")
    profiles = [str(profile) for profile in profiles]

    required_targets = contract.make_contract.required_targets

    spec_raw = _mapping(contract.raw.get("spec"))
    event_contract = _mapping(spec_raw.get("event_messaging_contract"))
    app_runtime_gitops_contract = _mapping(spec_raw.get("app_runtime_gitops_contract"))
    local_post_deploy_hook_contract = _mapping(spec_raw.get("local_post_deploy_hook_contract"))
    zero_downtime_contract = _mapping(spec_raw.get("zero_downtime_evolution_contract"))
    tenant_context_contract = _mapping(spec_raw.get("tenant_context_contract"))
    optional_runtime_contracts = [
        OptionalRuntimeContractMetadata(
            contract_id="event_messaging_contract",
            enabled_by_default=_bool_text(event_contract.get("enabled_by_default")),
            enable_flag=_string(event_contract.get("enable_flag")),
            summary="Canonical async envelope, versioning, outbox/inbox, and idempotency baseline.",
        ),
        OptionalRuntimeContractMetadata(
            contract_id="app_runtime_gitops_contract",
            enabled_by_default=_bool_text(app_runtime_gitops_contract.get("enabled_by_default")),
            enable_flag=_string(app_runtime_gitops_contract.get("enable_flag")),
            summary="Baseline app runtime GitOps workload scaffold and app-catalog delivery mapping contract.",
        ),
        OptionalRuntimeContractMetadata(
            contract_id="local_post_deploy_hook_contract",
            enabled_by_default=_bool_text(local_post_deploy_hook_contract.get("enabled_by_default")),
            enable_flag=_string(local_post_deploy_hook_contract.get("enable_flag")),
            summary="Local post-deploy extension point with strict/best-effort execution contract.",
        ),
        OptionalRuntimeContractMetadata(
            contract_id="zero_downtime_evolution_contract",
            enabled_by_default=_bool_text(zero_downtime_contract.get("enabled_by_default")),
            enable_flag=_string(zero_downtime_contract.get("enable_flag")),
            summary="Expand/migrate/contract policy for schema, API, and event rollouts.",
        ),
        OptionalRuntimeContractMetadata(
            contract_id="tenant_context_contract",
            enabled_by_default=_bool_text(tenant_context_contract.get("enabled_by_default")),
            enable_flag=_string(tenant_context_contract.get("enable_flag")),
            summary="Tenant/organization context propagation across identity, HTTP, async, and telemetry.",
        ),
    ]

    module_files = sorted(modules_dir.glob("*/module.contract.yaml"))
    modules = [_to_metadata(load_module_contract(path, repo_root)) for path in module_files]

    output = render_markdown(
        contract_name=contract.raw.get("metadata", {}).get("name", ""),
        contract_version=str(contract.raw.get("metadata", {}).get("version", "")),
        profiles=profiles,
        required_targets=required_targets,
        modules=modules,
        optional_runtime_contracts=optional_runtime_contracts,
        event_contract=event_contract,
        app_runtime_gitops_contract=app_runtime_gitops_contract,
        local_post_deploy_hook_contract=local_post_deploy_hook_contract,
        zero_downtime_contract=zero_downtime_contract,
        tenant_context_contract=tenant_context_contract,
    )

    if args.check:
        if not output_path.exists():
            print(f"contract metadata doc missing: {output_path}", file=sys.stderr)
            return 1
        current = output_path.read_text(encoding="utf-8")
        if current != output:
            print(
                f"contract metadata doc is out of date: {output_path}\n"
                "Run: python3 scripts/lib/docs/generate_contract_docs.py",
                file=sys.stderr,
            )
            return 1
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8")
    print(
        f"rendered contract metadata doc: {display_repo_path(repo_root, output_path)} "
        f"(profiles={len(profiles)} targets={len(required_targets)} modules={len(modules)})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
