#!/usr/bin/env bash
set -euo pipefail

# Canonical pinned versions for infra and platform dependencies.
TERRAFORM_VERSION="1.13.3"
HELM_VERSION="3.19.0"
KUBECTL_VERSION="1.34.1"
KIND_VERSION="0.30.0"
EXTERNAL_SECRETS_CHART_VERSION="2.2.0"
ARGOCD_CHART_VERSION="9.4.16"
CROSSPLANE_CHART_VERSION="2.2.0"
OTEL_COLLECTOR_CHART_VERSION="0.147.1"
GRAFANA_CHART_VERSION="9.5.4"
LOKI_CHART_VERSION="6.41.0"
TEMPO_CHART_VERSION="1.23.2"

# Optional-module local chart pins live here too so version drift stays
# contract-driven and `infra-audit-version` has one canonical source.
POSTGRES_HELM_CHART_VERSION_PIN="15.5.38"
OBJECT_STORAGE_HELM_CHART_VERSION_PIN="17.0.21"
RABBITMQ_HELM_CHART_VERSION_PIN="16.0.14"
NEO4J_HELM_CHART_VERSION_PIN="2026.1.4"
PUBLIC_ENDPOINTS_HELM_CHART_VERSION_PIN="4.15.1"
IAP_HELM_CHART_VERSION_PIN="10.4.0"
