fullnameOverride: "blueprint-rabbitmq"
image:
  registry: "docker.io"
  repository: "bitnamilegacy/rabbitmq"
  tag: "4.0.9-debian-12-r1"
auth:
  username: "marketplace"
  existingPasswordSecret: "blueprint-rabbitmq-auth"
  existingSecretPasswordKey: rabbitmq-password
service:
  type: ClusterIP
